In [38]:
import numpy as np
docs = np.array([
    [0.3, -1.2, 0.5, 0.9],
    [0.7, -2.7, 0.6, 0.1],
    [0.3, 0.01, 0.47, 2],
    [0.5, 2.2, 0.11, 3.0],
    [0.12, -0.7, 0.15, 0.25]
])
query = np.array([0.6, -1.5, 0.3, 0.2])
query_length = np.linalg.norm(query)
query_length


np.float64(1.6552945357246849)

In [39]:
q_norm = query / query_length
q_norm

array([ 0.36247326, -0.90618314,  0.18123663,  0.12082442])

In [40]:
q_norm_length_test = np.linalg.norm(q_norm)
q_norm_length_test

np.float64(1.0)

In [41]:
docs_lengths = np.linalg.norm(docs, axis=1, keepdims=True)
docs_lengths

array([[1.60934769],
       [2.85482048],
       [2.07629478],
       [3.75527629],
       [0.76772391]])

In [42]:
docs_norm = docs / docs_lengths
docs_norm

array([[ 0.18641093, -0.74564372,  0.31068488,  0.55923279],
       [ 0.24519931, -0.94576875,  0.21017083,  0.03502847],
       [ 0.14448815,  0.00481627,  0.22636478,  0.96325436],
       [ 0.133146  ,  0.58584238,  0.02929212,  0.79887597],
       [ 0.15630619, -0.91178611,  0.19538274,  0.3256379 ]])

In [43]:
docs_norm_test = np.linalg.norm(docs_norm, axis=1, keepdims=True)
docs_norm_test

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [44]:
similarities = docs_norm @ q_norm
similarities

array([ 0.8671352 ,  0.98824083,  0.2054189 , -0.3807861 ,  0.95765754])

In [45]:
best_ind_doc = np.argmax(similarities)
best_ind_doc

np.int64(1)